/**
 * Copyright (C) 2006-2017 INRIA and contributors
 * Spoon - http://spoon.gforge.inria.fr/
 *
 * This software is governed by the CeCILL-C License under French law and
 * abiding by the rules of distribution of free software. You can use, modify
 * and/or redistribute the software under the terms of the CeCILL-C license as
 * circulated by CEA, CNRS and INRIA at http://www.cecill.info.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the CeCILL-C License for more details.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
package spoon.reflect.visitor;
import java.lang.annotation.Annotation;
import spoon.reflect.code.CtAnnotationFieldAccess;
import spoon.reflect.code.CtArrayRead;
import spoon.reflect.code.CtArrayWrite;
import spoon.reflect.code.CtAssert;
import spoon.reflect.code.CtAssignment;
import spoon.reflect.code.CtBinaryOperator;
import spoon.reflect.code.CtBlock;
import spoon.reflect.code.CtBreak;
import spoon.reflect.code.CtCase;
import spoon.reflect.code.CtCatch;
import spoon.reflect.code.CtCatchVariable;
import spoon.reflect.code.CtCodeSnippetExpression;
import spoon.reflect.code.CtCodeSnippetStatement;
import spoon.reflect.code.CtComment;
import spoon.reflect.code.CtConditional;
import spoon.reflect.code.CtConstructorCall;
import spoon.reflect.code.CtContinue;
import spoon.reflect.code.CtDo;
import spoon.reflect.code.CtExecutableReferenceExpression;
import spoon.reflect.code.CtExpression;
import spoon.reflect.code.CtFieldRead;
import spoon.reflect.code.CtFieldWrite;
import spoon.reflect.code.CtFor;
import spoon.reflect.code.CtForEach;
import spoon.reflect.code.CtIf;
import spoon.reflect.code.CtInvocation;
import spoon.reflect.code.CtJavaDoc;
import spoon.reflect.code.CtJavaDocTag;
import spoon.reflect.code.CtLambda;
import spoon.reflect.code.CtLiteral;
import spoon.reflect.code.CtLocalVariable;
import spoon.reflect.code.CtNewArray;
import spoon.reflect.code.CtNewClass;
import spoon.reflect.code.CtOperatorAssignment;
import spoon.reflect.code.CtReturn;
import spoon.reflect.code.CtStatement;
import spoon.reflect.code.CtStatementList;
import spoon.reflect.code.CtSuperAccess;
import spoon.reflect.code.CtSwitch;
import spoon.reflect.code.CtSynchronized;
import spoon.reflect.code.CtThisAccess;
import spoon.reflect.code.CtThrow;
import spoon.reflect.code.CtTry;
import spoon.reflect.code.CtTryWithResource;
import spoon.reflect.code.CtTypeAccess;
import spoon.reflect.code.CtUnaryOperator;
import spoon.reflect.code.CtVariableRead;
import spoon.reflect.code.CtVariableWrite;
import spoon.reflect.code.CtWhile;
import spoon.reflect.declaration.CtAnnotation;
import spoon.reflect.declaration.CtAnnotationMethod;
import spoon.reflect.declaration.CtAnnotationType;
import spoon.reflect.declaration.CtAnonymousExecutable;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtConstructor;
import spoon.reflect.declaration.CtEnum;
import spoon.reflect.declaration.CtEnumValue;
import spoon.reflect.declaration.CtField;
import spoon.reflect.declaration.CtInterface;
import spoon.reflect.declaration.CtMethod;
import spoon.reflect.declaration.CtPackage;
import spoon.reflect.declaration.CtParameter;
import spoon.reflect.declaration.CtTypeParameter;
import spoon.reflect.reference.CtArrayTypeReference;
import spoon.reflect.reference.CtCatchVariableReference;
import spoon.reflect.reference.CtExecutableReference;
import spoon.reflect.reference.CtFieldReference;
import spoon.reflect.reference.CtIntersectionTypeReference;
import spoon.reflect.reference.CtLocalVariableReference;
import spoon.reflect.reference.CtPackageReference;
import spoon.reflect.reference.CtParameterReference;
import spoon.reflect.reference.CtTypeParameterReference;
import spoon.reflect.reference.CtTypeReference;
import spoon.reflect.reference.CtUnboundVariableReference;
import spoon.reflect.reference.CtWildcardReference;
/**
 * This visitor implements a deep-search scan on the model for 2 elements.
 *
 * Ensures that all children nodes are visited once, a visit means three method
 * calls, one call to "enter", one call to "exit" and one call to biScan.
 *
 * This class is generated automatically by the processor {@link spoon.generating.CtBiScannerGenerator}.
 *
 * Is used by EqualsVisitor.
 */
// autogenerated by CtBiScannerGenerator
public abstract class CtBiScannerDefault extends CtAbstractBiScanner {
    // autogenerated by CtBiScannerGenerator
    public <A extends Annotation> void visitCtAnnotation(final CtAnnotation<A> annotation) {
        CtAnnotation other = ((CtAnnotation) (this.stack.peek()));
        enter(annotation);
        biScan(annotation.getType(), other.getType());
        biScan(annotation.getComments(), other.getComments());
        biScan(annotation.getAnnotationType(), other.getAnnotationType());
        biScan(annotation.getAnnotations(), other.getAnnotations());
        biScan(annotation.getValues().values(), other.getValues().values());
        exit(annotation);
    }

    // autogenerated by CtBiScannerGenerator
    public <A extends Annotation> void visitCtAnnotationType(final CtAnnotationType<A> annotationType) {
        CtAnnotationType other = ((CtAnnotationType) (this.stack.peek()));
        enter(annotationType);
        biScan(annotationType.getAnnotations(), other.getAnnotations());
        biScan(annotationType.getTypeMembers(), other.getTypeMembers());
        biScan(annotationType.getComments(), other.getComments());
        exit(annotationType);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtAnonymousExecutable(final CtAnonymousExecutable anonymousExec) {
        CtAnonymousExecutable other = ((CtAnonymousExecutable) (this.stack.peek()));
        enter(anonymousExec);
        biScan(anonymousExec.getAnnotations(), other.getAnnotations());
        biScan(anonymousExec.getBody(), other.getBody());
        biScan(anonymousExec.getComments(), other.getComments());
        exit(anonymousExec);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtArrayRead(final CtArrayRead<T> arrayRead) {
        CtArrayRead other = ((CtArrayRead) (this.stack.peek()));
        enter(arrayRead);
        biScan(arrayRead.getAnnotations(), other.getAnnotations());
        biScan(arrayRead.getType(), other.getType());
        biScan(arrayRead.getTypeCasts(), other.getTypeCasts());
        biScan(arrayRead.getTarget(), other.getTarget());
        biScan(arrayRead.getIndexExpression(), other.getIndexExpression());
        biScan(arrayRead.getComments(), other.getComments());
        exit(arrayRead);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtArrayWrite(final CtArrayWrite<T> arrayWrite) {
        CtArrayWrite other = ((CtArrayWrite) (this.stack.peek()));
        enter(arrayWrite);
        biScan(arrayWrite.getAnnotations(), other.getAnnotations());
        biScan(arrayWrite.getType(), other.getType());
        biScan(arrayWrite.getTypeCasts(), other.getTypeCasts());
        biScan(arrayWrite.getTarget(), other.getTarget());
        biScan(arrayWrite.getIndexExpression(), other.getIndexExpression());
        biScan(arrayWrite.getComments(), other.getComments());
        exit(arrayWrite);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtArrayTypeReference(final CtArrayTypeReference<T> reference) {
        CtArrayTypeReference other = ((CtArrayTypeReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getComments(), other.getComments());
        biScan(reference.getPackage(), other.getPackage());
        biScan(reference.getDeclaringType(), other.getDeclaringType());
        biScan(reference.getComponentType(), other.getComponentType());
        biScan(reference.getActualTypeArguments(), other.getActualTypeArguments());
        biScan(reference.getAnnotations(), other.getAnnotations());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtAssert(final CtAssert<T> asserted) {
        CtAssert other = ((CtAssert) (this.stack.peek()));
        enter(asserted);
        biScan(asserted.getAnnotations(), other.getAnnotations());
        biScan(asserted.getAssertExpression(), other.getAssertExpression());
        biScan(asserted.getExpression(), other.getExpression());
        biScan(asserted.getComments(), other.getComments());
        exit(asserted);
    }

    // autogenerated by CtBiScannerGenerator
    public <T, A extends T> void visitCtAssignment(final CtAssignment<T, A> assignement) {
        CtAssignment other = ((CtAssignment) (this.stack.peek()));
        enter(assignement);
        biScan(assignement.getAnnotations(), other.getAnnotations());
        biScan(assignement.getType(), other.getType());
        biScan(assignement.getTypeCasts(), other.getTypeCasts());
        biScan(assignement.getAssigned(), other.getAssigned());
        biScan(assignement.getAssignment(), other.getAssignment());
        biScan(assignement.getComments(), other.getComments());
        exit(assignement);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtBinaryOperator(final CtBinaryOperator<T> operator) {
        CtBinaryOperator other = ((CtBinaryOperator) (this.stack.peek()));
        enter(operator);
        biScan(operator.getAnnotations(), other.getAnnotations());
        biScan(operator.getType(), other.getType());
        biScan(operator.getTypeCasts(), other.getTypeCasts());
        biScan(operator.getLeftHandOperand(), other.getLeftHandOperand());
        biScan(operator.getRightHandOperand(), other.getRightHandOperand());
        biScan(operator.getComments(), other.getComments());
        exit(operator);
    }

    // autogenerated by CtBiScannerGenerator
    public <R> void visitCtBlock(final CtBlock<R> block) {
        CtBlock other = ((CtBlock) (this.stack.peek()));
        enter(block);
        biScan(block.getAnnotations(), other.getAnnotations());
        biScan(block.getStatements(), other.getStatements());
        biScan(block.getComments(), other.getComments());
        exit(block);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtBreak(final CtBreak breakStatement) {
        CtBreak other = ((CtBreak) (this.stack.peek()));
        enter(breakStatement);
        biScan(breakStatement.getAnnotations(), other.getAnnotations());
        biScan(breakStatement.getComments(), other.getComments());
        exit(breakStatement);
    }

    // autogenerated by CtBiScannerGenerator
    public <S> void visitCtCase(final CtCase<S> caseStatement) {
        CtCase other = ((CtCase) (this.stack.peek()));
        enter(caseStatement);
        biScan(caseStatement.getAnnotations(), other.getAnnotations());
        biScan(caseStatement.getCaseExpression(), other.getCaseExpression());
        biScan(caseStatement.getStatements(), other.getStatements());
        biScan(caseStatement.getComments(), other.getComments());
        exit(caseStatement);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtCatch(final CtCatch catchBlock) {
        CtCatch other = ((CtCatch) (this.stack.peek()));
        enter(catchBlock);
        biScan(catchBlock.getAnnotations(), other.getAnnotations());
        biScan(catchBlock.getParameter(), other.getParameter());
        biScan(catchBlock.getBody(), other.getBody());
        biScan(catchBlock.getComments(), other.getComments());
        exit(catchBlock);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtClass(final CtClass<T> ctClass) {
        CtClass other = ((CtClass) (this.stack.peek()));
        enter(ctClass);
        biScan(ctClass.getAnnotations(), other.getAnnotations());
        biScan(ctClass.getSuperclass(), other.getSuperclass());
        biScan(ctClass.getSuperInterfaces(), other.getSuperInterfaces());
        biScan(ctClass.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
        biScan(ctClass.getTypeMembers(), other.getTypeMembers());
        biScan(ctClass.getComments(), other.getComments());
        exit(ctClass);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public void visitCtTypeParameter(CtTypeParameter typeParameter) {
        CtTypeParameter other = ((CtTypeParameter) (this.stack.peek()));
        enter(typeParameter);
        biScan(typeParameter.getAnnotations(), other.getAnnotations());
        biScan(typeParameter.getSuperclass(), other.getSuperclass());
        biScan(typeParameter.getComments(), other.getComments());
        exit(typeParameter);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtConditional(final CtConditional<T> conditional) {
        CtConditional other = ((CtConditional) (this.stack.peek()));
        enter(conditional);
        biScan(conditional.getType(), other.getType());
        biScan(conditional.getAnnotations(), other.getAnnotations());
        biScan(conditional.getCondition(), other.getCondition());
        biScan(conditional.getThenExpression(), other.getThenExpression());
        biScan(conditional.getElseExpression(), other.getElseExpression());
        biScan(conditional.getComments(), other.getComments());
        biScan(conditional.getTypeCasts(), other.getTypeCasts());
        exit(conditional);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtConstructor(final CtConstructor<T> c) {
        CtConstructor other = ((CtConstructor) (this.stack.peek()));
        enter(c);
        biScan(c.getAnnotations(), other.getAnnotations());
        biScan(c.getParameters(), other.getParameters());
        biScan(c.getThrownTypes(), other.getThrownTypes());
        biScan(c.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
        biScan(c.getBody(), other.getBody());
        biScan(c.getComments(), other.getComments());
        exit(c);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtContinue(final CtContinue continueStatement) {
        CtContinue other = ((CtContinue) (this.stack.peek()));
        enter(continueStatement);
        biScan(continueStatement.getAnnotations(), other.getAnnotations());
        biScan(continueStatement.getComments(), other.getComments());
        exit(continueStatement);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtDo(final CtDo doLoop) {
        CtDo other = ((CtDo) (this.stack.peek()));
        enter(doLoop);
        biScan(doLoop.getAnnotations(), other.getAnnotations());
        biScan(doLoop.getLoopingExpression(), other.getLoopingExpression());
        biScan(doLoop.getBody(), other.getBody());
        biScan(doLoop.getComments(), other.getComments());
        exit(doLoop);
    }

    // autogenerated by CtBiScannerGenerator
    public <T extends Enum<?>> void visitCtEnum(final CtEnum<T> ctEnum) {
        CtEnum other = ((CtEnum) (this.stack.peek()));
        enter(ctEnum);
        biScan(ctEnum.getAnnotations(), other.getAnnotations());
        biScan(ctEnum.getSuperInterfaces(), other.getSuperInterfaces());
        biScan(ctEnum.getTypeMembers(), other.getTypeMembers());
        biScan(ctEnum.getEnumValues(), other.getEnumValues());
        biScan(ctEnum.getComments(), other.getComments());
        exit(ctEnum);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtExecutableReference(final CtExecutableReference<T> reference) {
        CtExecutableReference other = ((CtExecutableReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getDeclaringType(), other.getDeclaringType());
        biScan(reference.getType(), other.getType());
        biScan(reference.getParameters(), other.getParameters());
        biScan(reference.getActualTypeArguments(), other.getActualTypeArguments());
        biScan(reference.getAnnotations(), other.getAnnotations());
        biScan(reference.getComments(), other.getComments());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtField(final CtField<T> f) {
        CtField other = ((CtField) (this.stack.peek()));
        enter(f);
        biScan(f.getAnnotations(), other.getAnnotations());
        biScan(f.getType(), other.getType());
        biScan(f.getDefaultExpression(), other.getDefaultExpression());
        biScan(f.getComments(), other.getComments());
        exit(f);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtEnumValue(final CtEnumValue<T> enumValue) {
        CtEnumValue other = ((CtEnumValue) (this.stack.peek()));
        enter(enumValue);
        biScan(enumValue.getAnnotations(), other.getAnnotations());
        biScan(enumValue.getType(), other.getType());
        biScan(enumValue.getDefaultExpression(), other.getDefaultExpression());
        biScan(enumValue.getComments(), other.getComments());
        exit(enumValue);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtThisAccess(final CtThisAccess<T> thisAccess) {
        CtThisAccess other = ((CtThisAccess) (this.stack.peek()));
        enter(thisAccess);
        biScan(thisAccess.getComments(), other.getComments());
        biScan(thisAccess.getAnnotations(), other.getAnnotations());
        biScan(thisAccess.getType(), other.getType());
        biScan(thisAccess.getTypeCasts(), other.getTypeCasts());
        biScan(thisAccess.getTarget(), other.getTarget());
        exit(thisAccess);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtAnnotationFieldAccess(final CtAnnotationFieldAccess<T> annotationFieldAccess) {
        CtAnnotationFieldAccess other = ((CtAnnotationFieldAccess) (this.stack.peek()));
        enter(annotationFieldAccess);
        biScan(annotationFieldAccess.getComments(), other.getComments());
        biScan(annotationFieldAccess.getAnnotations(), other.getAnnotations());
        biScan(annotationFieldAccess.getTypeCasts(), other.getTypeCasts());
        biScan(annotationFieldAccess.getTarget(), other.getTarget());
        biScan(annotationFieldAccess.getType(), other.getType());
        biScan(annotationFieldAccess.getVariable(), other.getVariable());
        exit(annotationFieldAccess);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtFieldReference(final CtFieldReference<T> reference) {
        CtFieldReference other = ((CtFieldReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getDeclaringType(), other.getDeclaringType());
        biScan(reference.getType(), other.getType());
        biScan(reference.getAnnotations(), other.getAnnotations());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtFor(final CtFor forLoop) {
        CtFor other = ((CtFor) (this.stack.peek()));
        enter(forLoop);
        biScan(forLoop.getAnnotations(), other.getAnnotations());
        biScan(forLoop.getForInit(), other.getForInit());
        biScan(forLoop.getExpression(), other.getExpression());
        biScan(forLoop.getForUpdate(), other.getForUpdate());
        biScan(forLoop.getBody(), other.getBody());
        biScan(forLoop.getComments(), other.getComments());
        exit(forLoop);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtForEach(final CtForEach foreach) {
        CtForEach other = ((CtForEach) (this.stack.peek()));
        enter(foreach);
        biScan(foreach.getAnnotations(), other.getAnnotations());
        biScan(foreach.getVariable(), other.getVariable());
        biScan(foreach.getExpression(), other.getExpression());
        biScan(foreach.getBody(), other.getBody());
        biScan(foreach.getComments(), other.getComments());
        exit(foreach);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtIf(final CtIf ifElement) {
        CtIf other = ((CtIf) (this.stack.peek()));
        enter(ifElement);
        biScan(ifElement.getAnnotations(), other.getAnnotations());
        biScan(ifElement.getCondition(), other.getCondition());
        biScan(((CtStatement) (ifElement.getThenStatement())), other.getThenStatement());
        biScan(((CtStatement) (ifElement.getElseStatement())), other.getElseStatement());
        biScan(ifElement.getComments(), other.getComments());
        exit(ifElement);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtInterface(final CtInterface<T> intrface) {
        CtInterface other = ((CtInterface) (this.stack.peek()));
        enter(intrface);
        biScan(intrface.getAnnotations(), other.getAnnotations());
        biScan(intrface.getSuperInterfaces(), other.getSuperInterfaces());
        biScan(intrface.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
        biScan(intrface.getTypeMembers(), other.getTypeMembers());
        biScan(intrface.getComments(), other.getComments());
        exit(intrface);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtInvocation(final CtInvocation<T> invocation) {
        CtInvocation other = ((CtInvocation) (this.stack.peek()));
        enter(invocation);
        biScan(invocation.getAnnotations(), other.getAnnotations());
        biScan(invocation.getTypeCasts(), other.getTypeCasts());
        biScan(invocation.getTarget(), other.getTarget());
        biScan(invocation.getExecutable(), other.getExecutable());
        biScan(invocation.getArguments(), other.getArguments());
        biScan(invocation.getComments(), other.getComments());
        exit(invocation);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtLiteral(final CtLiteral<T> literal) {
        CtLiteral other = ((CtLiteral) (this.stack.peek()));
        enter(literal);
        biScan(literal.getAnnotations(), other.getAnnotations());
        biScan(literal.getType(), other.getType());
        biScan(literal.getTypeCasts(), other.getTypeCasts());
        biScan(literal.getComments(), other.getComments());
        exit(literal);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtLocalVariable(final CtLocalVariable<T> localVariable) {
        CtLocalVariable other = ((CtLocalVariable) (this.stack.peek()));
        enter(localVariable);
        biScan(localVariable.getAnnotations(), other.getAnnotations());
        biScan(localVariable.getType(), other.getType());
        biScan(localVariable.getDefaultExpression(), other.getDefaultExpression());
        biScan(localVariable.getComments(), other.getComments());
        exit(localVariable);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtLocalVariableReference(final CtLocalVariableReference<T> reference) {
        CtLocalVariableReference other = ((CtLocalVariableReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getType(), other.getType());
        biScan(reference.getAnnotations(), other.getAnnotations());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtCatchVariable(final CtCatchVariable<T> catchVariable) {
        CtCatchVariable other = ((CtCatchVariable) (this.stack.peek()));
        enter(catchVariable);
        biScan(catchVariable.getComments(), other.getComments());
        biScan(catchVariable.getAnnotations(), other.getAnnotations());
        biScan(catchVariable.getDefaultExpression(), other.getDefaultExpression());
        biScan(catchVariable.getType(), other.getType());
        biScan(catchVariable.getMultiTypes(), other.getMultiTypes());
        exit(catchVariable);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtCatchVariableReference(final CtCatchVariableReference<T> reference) {
        CtCatchVariableReference other = ((CtCatchVariableReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getComments(), other.getComments());
        biScan(reference.getType(), other.getType());
        biScan(reference.getAnnotations(), other.getAnnotations());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtMethod(final CtMethod<T> m) {
        CtMethod other = ((CtMethod) (this.stack.peek()));
        enter(m);
        biScan(m.getAnnotations(), other.getAnnotations());
        biScan(m.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
        biScan(m.getType(), other.getType());
        biScan(m.getParameters(), other.getParameters());
        biScan(m.getThrownTypes(), other.getThrownTypes());
        biScan(m.getBody(), other.getBody());
        biScan(m.getComments(), other.getComments());
        exit(m);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtAnnotationMethod(CtAnnotationMethod<T> annotationMethod) {
        CtAnnotationMethod other = ((CtAnnotationMethod) (this.stack.peek()));
        enter(annotationMethod);
        biScan(annotationMethod.getAnnotations(), other.getAnnotations());
        biScan(annotationMethod.getType(), other.getType());
        biScan(annotationMethod.getDefaultExpression(), other.getDefaultExpression());
        biScan(annotationMethod.getComments(), other.getComments());
        exit(annotationMethod);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtNewArray(final CtNewArray<T> newArray) {
        CtNewArray other = ((CtNewArray) (this.stack.peek()));
        enter(newArray);
        biScan(newArray.getAnnotations(), other.getAnnotations());
        biScan(newArray.getType(), other.getType());
        biScan(newArray.getTypeCasts(), other.getTypeCasts());
        biScan(newArray.getElements(), other.getElements());
        biScan(newArray.getDimensionExpressions(), other.getDimensionExpressions());
        biScan(newArray.getComments(), other.getComments());
        exit(newArray);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtConstructorCall(final CtConstructorCall<T> ctConstructorCall) {
        CtConstructorCall other = ((CtConstructorCall) (this.stack.peek()));
        enter(ctConstructorCall);
        biScan(ctConstructorCall.getAnnotations(), other.getAnnotations());
        biScan(ctConstructorCall.getTypeCasts(), other.getTypeCasts());
        biScan(ctConstructorCall.getExecutable(), other.getExecutable());
        biScan(ctConstructorCall.getTarget(), other.getTarget());
        biScan(ctConstructorCall.getArguments(), other.getArguments());
        biScan(ctConstructorCall.getComments(), other.getComments());
        exit(ctConstructorCall);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtNewClass(final CtNewClass<T> newClass) {
        CtNewClass other = ((CtNewClass) (this.stack.peek()));
        enter(newClass);
        biScan(newClass.getAnnotations(), other.getAnnotations());
        biScan(newClass.getTypeCasts(), other.getTypeCasts());
        biScan(newClass.getExecutable(), other.getExecutable());
        biScan(newClass.getTarget(), other.getTarget());
        biScan(newClass.getArguments(), other.getArguments());
        biScan(newClass.getAnonymousClass(), other.getAnonymousClass());
        biScan(newClass.getComments(), other.getComments());
        exit(newClass);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtLambda(final CtLambda<T> lambda) {
        CtLambda other = ((CtLambda) (this.stack.peek()));
        enter(lambda);
        biScan(lambda.getAnnotations(), other.getAnnotations());
        biScan(lambda.getType(), other.getType());
        biScan(lambda.getTypeCasts(), other.getTypeCasts());
        biScan(lambda.getParameters(), other.getParameters());
        biScan(lambda.getThrownTypes(), other.getThrownTypes());
        biScan(lambda.getBody(), other.getBody());
        biScan(lambda.getExpression(), other.getExpression());
        biScan(lambda.getComments(), other.getComments());
        exit(lambda);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T, E extends CtExpression<?>> void visitCtExecutableReferenceExpression(final CtExecutableReferenceExpression<T, E> expression) {
        CtExecutableReferenceExpression other = ((CtExecutableReferenceExpression) (this.stack.peek()));
        enter(expression);
        biScan(expression.getComments(), other.getComments());
        biScan(expression.getAnnotations(), other.getAnnotations());
        biScan(expression.getType(), other.getType());
        biScan(expression.getTypeCasts(), other.getTypeCasts());
        biScan(expression.getExecutable(), other.getExecutable());
        biScan(expression.getTarget(), other.getTarget());
        exit(expression);
    }

    // autogenerated by CtBiScannerGenerator
    public <T, A extends T> void visitCtOperatorAssignment(final CtOperatorAssignment<T, A> assignment) {
        CtOperatorAssignment other = ((CtOperatorAssignment) (this.stack.peek()));
        enter(assignment);
        biScan(assignment.getAnnotations(), other.getAnnotations());
        biScan(assignment.getType(), other.getType());
        biScan(assignment.getTypeCasts(), other.getTypeCasts());
        biScan(assignment.getAssigned(), other.getAssigned());
        biScan(assignment.getAssignment(), other.getAssignment());
        biScan(assignment.getComments(), other.getComments());
        exit(assignment);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtPackage(final CtPackage ctPackage) {
        CtPackage other = ((CtPackage) (this.stack.peek()));
        enter(ctPackage);
        biScan(ctPackage.getAnnotations(), other.getAnnotations());
        biScan(ctPackage.getPackages(), other.getPackages());
        biScan(ctPackage.getTypes(), other.getTypes());
        biScan(ctPackage.getComments(), other.getComments());
        exit(ctPackage);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtPackageReference(final CtPackageReference reference) {
        CtPackageReference other = ((CtPackageReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getAnnotations(), other.getAnnotations());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtParameter(final CtParameter<T> parameter) {
        CtParameter other = ((CtParameter) (this.stack.peek()));
        enter(parameter);
        biScan(parameter.getAnnotations(), other.getAnnotations());
        biScan(parameter.getType(), other.getType());
        biScan(parameter.getComments(), other.getComments());
        exit(parameter);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtParameterReference(final CtParameterReference<T> reference) {
        CtParameterReference other = ((CtParameterReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getType(), other.getType());
        biScan(reference.getAnnotations(), other.getAnnotations());
        biScan(reference.getDeclaringExecutable(), other.getDeclaringExecutable());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <R> void visitCtReturn(final CtReturn<R> returnStatement) {
        CtReturn other = ((CtReturn) (this.stack.peek()));
        enter(returnStatement);
        biScan(returnStatement.getAnnotations(), other.getAnnotations());
        biScan(returnStatement.getReturnedExpression(), other.getReturnedExpression());
        biScan(returnStatement.getComments(), other.getComments());
        exit(returnStatement);
    }

    // autogenerated by CtBiScannerGenerator
    public <R> void visitCtStatementList(final CtStatementList statements) {
        CtStatementList other = ((CtStatementList) (this.stack.peek()));
        enter(statements);
        biScan(statements.getAnnotations(), other.getAnnotations());
        biScan(statements.getStatements(), other.getStatements());
        biScan(statements.getComments(), other.getComments());
        exit(statements);
    }

    // autogenerated by CtBiScannerGenerator
    public <S> void visitCtSwitch(final CtSwitch<S> switchStatement) {
        CtSwitch other = ((CtSwitch) (this.stack.peek()));
        enter(switchStatement);
        biScan(switchStatement.getAnnotations(), other.getAnnotations());
        biScan(switchStatement.getSelector(), other.getSelector());
        biScan(switchStatement.getCases(), other.getCases());
        biScan(switchStatement.getComments(), other.getComments());
        exit(switchStatement);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtSynchronized(final CtSynchronized synchro) {
        CtSynchronized other = ((CtSynchronized) (this.stack.peek()));
        enter(synchro);
        biScan(synchro.getAnnotations(), other.getAnnotations());
        biScan(synchro.getExpression(), other.getExpression());
        biScan(synchro.getBlock(), other.getBlock());
        biScan(synchro.getComments(), other.getComments());
        exit(synchro);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtThrow(final CtThrow throwStatement) {
        CtThrow other = ((CtThrow) (this.stack.peek()));
        enter(throwStatement);
        biScan(throwStatement.getAnnotations(), other.getAnnotations());
        biScan(throwStatement.getThrownExpression(), other.getThrownExpression());
        biScan(throwStatement.getComments(), other.getComments());
        exit(throwStatement);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtTry(final CtTry tryBlock) {
        CtTry other = ((CtTry) (this.stack.peek()));
        enter(tryBlock);
        biScan(tryBlock.getAnnotations(), other.getAnnotations());
        biScan(tryBlock.getBody(), other.getBody());
        biScan(tryBlock.getCatchers(), other.getCatchers());
        biScan(tryBlock.getFinalizer(), other.getFinalizer());
        biScan(tryBlock.getComments(), other.getComments());
        exit(tryBlock);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public void visitCtTryWithResource(final CtTryWithResource tryWithResource) {
        CtTryWithResource other = ((CtTryWithResource) (this.stack.peek()));
        enter(tryWithResource);
        biScan(tryWithResource.getAnnotations(), other.getAnnotations());
        biScan(tryWithResource.getResources(), other.getResources());
        biScan(tryWithResource.getBody(), other.getBody());
        biScan(tryWithResource.getCatchers(), other.getCatchers());
        biScan(tryWithResource.getFinalizer(), other.getFinalizer());
        biScan(tryWithResource.getComments(), other.getComments());
        exit(tryWithResource);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtTypeParameterReference(final CtTypeParameterReference ref) {
        CtTypeParameterReference other = ((CtTypeParameterReference) (this.stack.peek()));
        enter(ref);
        biScan(ref.getPackage(), other.getPackage());
        biScan(ref.getDeclaringType(), other.getDeclaringType());
        biScan(ref.getAnnotations(), other.getAnnotations());
        biScan(ref.getBoundingType(), other.getBoundingType());
        exit(ref);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public void visitCtWildcardReference(CtWildcardReference wildcardReference) {
        CtWildcardReference other = ((CtWildcardReference) (this.stack.peek()));
        enter(wildcardReference);
        biScan(wildcardReference.getPackage(), other.getPackage());
        biScan(wildcardReference.getDeclaringType(), other.getDeclaringType());
        biScan(wildcardReference.getAnnotations(), other.getAnnotations());
        biScan(wildcardReference.getBoundingType(), other.getBoundingType());
        exit(wildcardReference);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtIntersectionTypeReference(final CtIntersectionTypeReference<T> reference) {
        CtIntersectionTypeReference other = ((CtIntersectionTypeReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getPackage(), other.getPackage());
        biScan(reference.getDeclaringType(), other.getDeclaringType());
        biScan(reference.getAnnotations(), other.getAnnotations());
        biScan(reference.getBounds(), other.getBounds());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtTypeReference(final CtTypeReference<T> reference) {
        CtTypeReference other = ((CtTypeReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getPackage(), other.getPackage());
        biScan(reference.getDeclaringType(), other.getDeclaringType());
        biScan(reference.getActualTypeArguments(), other.getActualTypeArguments());
        biScan(reference.getAnnotations(), other.getAnnotations());
        biScan(reference.getComments(), other.getComments());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtTypeAccess(final CtTypeAccess<T> typeAccess) {
        CtTypeAccess other = ((CtTypeAccess) (this.stack.peek()));
        enter(typeAccess);
        biScan(typeAccess.getAnnotations(), other.getAnnotations());
        biScan(typeAccess.getTypeCasts(), other.getTypeCasts());
        biScan(typeAccess.getAccessedType(), other.getAccessedType());
        biScan(typeAccess.getComments(), other.getComments());
        exit(typeAccess);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtUnaryOperator(final CtUnaryOperator<T> operator) {
        CtUnaryOperator other = ((CtUnaryOperator) (this.stack.peek()));
        enter(operator);
        biScan(operator.getAnnotations(), other.getAnnotations());
        biScan(operator.getType(), other.getType());
        biScan(operator.getTypeCasts(), other.getTypeCasts());
        biScan(operator.getOperand(), other.getOperand());
        biScan(operator.getComments(), other.getComments());
        exit(operator);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtVariableRead(final CtVariableRead<T> variableRead) {
        CtVariableRead other = ((CtVariableRead) (this.stack.peek()));
        enter(variableRead);
        biScan(variableRead.getAnnotations(), other.getAnnotations());
        biScan(variableRead.getTypeCasts(), other.getTypeCasts());
        biScan(variableRead.getVariable(), other.getVariable());
        biScan(variableRead.getComments(), other.getComments());
        exit(variableRead);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtVariableWrite(final CtVariableWrite<T> variableWrite) {
        CtVariableWrite other = ((CtVariableWrite) (this.stack.peek()));
        enter(variableWrite);
        biScan(variableWrite.getAnnotations(), other.getAnnotations());
        biScan(variableWrite.getTypeCasts(), other.getTypeCasts());
        biScan(variableWrite.getVariable(), other.getVariable());
        biScan(variableWrite.getComments(), other.getComments());
        exit(variableWrite);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtWhile(final CtWhile whileLoop) {
        CtWhile other = ((CtWhile) (this.stack.peek()));
        enter(whileLoop);
        biScan(whileLoop.getAnnotations(), other.getAnnotations());
        biScan(whileLoop.getLoopingExpression(), other.getLoopingExpression());
        biScan(whileLoop.getBody(), other.getBody());
        biScan(whileLoop.getComments(), other.getComments());
        exit(whileLoop);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtCodeSnippetExpression(final CtCodeSnippetExpression<T> expression) {
        CtCodeSnippetExpression other = ((CtCodeSnippetExpression) (this.stack.peek()));
        enter(expression);
        biScan(expression.getType(), other.getType());
        biScan(expression.getComments(), other.getComments());
        biScan(expression.getAnnotations(), other.getAnnotations());
        biScan(expression.getTypeCasts(), other.getTypeCasts());
        exit(expression);
    }

    // autogenerated by CtBiScannerGenerator
    public void visitCtCodeSnippetStatement(final CtCodeSnippetStatement statement) {
        CtCodeSnippetStatement other = ((CtCodeSnippetStatement) (this.stack.peek()));
        enter(statement);
        biScan(statement.getComments(), other.getComments());
        biScan(statement.getAnnotations(), other.getAnnotations());
        exit(statement);
    }

    // autogenerated by CtBiScannerGenerator
    public <T> void visitCtUnboundVariableReference(final CtUnboundVariableReference<T> reference) {
        CtUnboundVariableReference other = ((CtUnboundVariableReference) (this.stack.peek()));
        enter(reference);
        biScan(reference.getType(), other.getType());
        exit(reference);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtFieldRead(final CtFieldRead<T> fieldRead) {
        CtFieldRead other = ((CtFieldRead) (this.stack.peek()));
        enter(fieldRead);
        biScan(fieldRead.getAnnotations(), other.getAnnotations());
        biScan(fieldRead.getTypeCasts(), other.getTypeCasts());
        biScan(fieldRead.getTarget(), other.getTarget());
        biScan(fieldRead.getVariable(), other.getVariable());
        biScan(fieldRead.getComments(), other.getComments());
        exit(fieldRead);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtFieldWrite(final CtFieldWrite<T> fieldWrite) {
        CtFieldWrite other = ((CtFieldWrite) (this.stack.peek()));
        enter(fieldWrite);
        biScan(fieldWrite.getAnnotations(), other.getAnnotations());
        biScan(fieldWrite.getTypeCasts(), other.getTypeCasts());
        biScan(fieldWrite.getTarget(), other.getTarget());
        biScan(fieldWrite.getVariable(), other.getVariable());
        biScan(fieldWrite.getComments(), other.getComments());
        exit(fieldWrite);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public <T> void visitCtSuperAccess(final CtSuperAccess<T> f) {
        CtSuperAccess other = ((CtSuperAccess) (this.stack.peek()));
        enter(f);
        biScan(f.getType(), other.getType());
        biScan(f.getComments(), other.getComments());
        biScan(f.getAnnotations(), other.getAnnotations());
        biScan(f.getTypeCasts(), other.getTypeCasts());
        biScan(f.getTarget(), other.getTarget());
        biScan(f.getVariable(), other.getVariable());
        exit(f);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public void visitCtComment(final CtComment comment) {
        CtComment other = ((CtComment) (this.stack.peek()));
        enter(comment);
        biScan(comment.getComments(), other.getComments());
        biScan(comment.getAnnotations(), other.getAnnotations());
        exit(comment);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public void visitCtJavaDoc(final CtJavaDoc javaDoc) {
        CtJavaDoc other = ((CtJavaDoc) (this.stack.peek()));
        enter(javaDoc);
        biScan(javaDoc.getComments(), other.getComments());
        biScan(javaDoc.getAnnotations(), other.getAnnotations());
        biScan(javaDoc.getTags(), other.getTags());
        exit(javaDoc);
    }

    // autogenerated by CtBiScannerGenerator
    @Override
    public void visitCtJavaDocTag(final CtJavaDocTag docTag) {
        CtJavaDocTag other = ((CtJavaDocTag) (this.stack.peek()));
        enter(docTag);
        biScan(docTag.getComments(), other.getComments());
        biScan(docTag.getAnnotations(), other.getAnnotations());
        exit(docTag);
    }
}